modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="haisistente"
version="1.0.0"
displayName="haisistente"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="INTEL, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.haisistente]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.haisistente]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haisistente]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haisistente]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration